all: | fastARG ARGweaver RentPlus ftprime
	make -C fastARG
	make -C ARGweaver
	make -C RentPlus
	make -C ftprime

fastARG: 
	git clone https://github.com/lh3/fastARG

ARGweaver: 
	git clone https://github.com/CshlSiepelLab/argweaver
	
RentPlus:
	git clone https://github.com/SajadMirzaei/RentPlus

ftprime:
	git clone https://github.com/ashander/ftprime
	

